<?php

namespace Database\Seeders\Badaso\CRUD;

use Illuminate\Database\Seeder;
use Uasoft\Badaso\Facades\Badaso;

class PageContactSetupCRUDDataRowAdded extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     *
     * @throws Exception
     */
    public function run()
    {
        \DB::beginTransaction();

        try {

            $data_type = Badaso::model('DataType')::where('name', 'page_contact_setup')->first();

            \DB::table('badaso_data_rows')->insert(array (
                0 => 
                array (
                    'data_type_id' => $data_type->id,
                    'field' => 'id',
                    'type' => 'number',
                    'display_name' => 'Id',
                    'required' => '1',
                    'browse' => '0',
                    'read' => '0',
                    'edit' => '0',
                    'add' => '0',
                    'delete' => '0',
                    'details' => '{}',
                    'relation' => NULL,
                    'order' => '1',
                ),
                1 => 
                array (
                    'data_type_id' => $data_type->id,
                    'field' => 'title_1',
                    'type' => 'text',
                    'display_name' => 'Title 1',
                    'required' => '0',
                    'browse' => '1',
                    'read' => '1',
                    'edit' => '1',
                    'add' => '1',
                    'delete' => '1',
                    'details' => '{}',
                    'relation' => NULL,
                    'order' => '2',
                ),
                2 => 
                array (
                    'data_type_id' => $data_type->id,
                    'field' => 'headline_1',
                    'type' => 'text',
                    'display_name' => 'Headline 1',
                    'required' => '0',
                    'browse' => '0',
                    'read' => '1',
                    'edit' => '1',
                    'add' => '1',
                    'delete' => '0',
                    'details' => '{}',
                    'relation' => NULL,
                    'order' => '3',
                ),
                3 => 
                array (
                    'data_type_id' => $data_type->id,
                    'field' => 'description_1',
                    'type' => 'text',
                    'display_name' => 'Description 1',
                    'required' => '0',
                    'browse' => '0',
                    'read' => '1',
                    'edit' => '1',
                    'add' => '1',
                    'delete' => '0',
                    'details' => '{}',
                    'relation' => NULL,
                    'order' => '4',
                ),
                4 => 
                array (
                    'data_type_id' => $data_type->id,
                    'field' => 'title_2',
                    'type' => 'text',
                    'display_name' => 'Title 2',
                    'required' => '0',
                    'browse' => '0',
                    'read' => '1',
                    'edit' => '1',
                    'add' => '1',
                    'delete' => '0',
                    'details' => '{}',
                    'relation' => NULL,
                    'order' => '5',
                ),
                5 => 
                array (
                    'data_type_id' => $data_type->id,
                    'field' => 'headline_2',
                    'type' => 'text',
                    'display_name' => 'Headline 2',
                    'required' => '0',
                    'browse' => '0',
                    'read' => '1',
                    'edit' => '1',
                    'add' => '1',
                    'delete' => '0',
                    'details' => '{}',
                    'relation' => NULL,
                    'order' => '6',
                ),
                6 => 
                array (
                    'data_type_id' => $data_type->id,
                    'field' => 'description_2',
                    'type' => 'text',
                    'display_name' => 'Description 2',
                    'required' => '0',
                    'browse' => '0',
                    'read' => '1',
                    'edit' => '1',
                    'add' => '1',
                    'delete' => '0',
                    'details' => '{}',
                    'relation' => NULL,
                    'order' => '7',
                ),
                7 => 
                array (
                    'data_type_id' => $data_type->id,
                    'field' => 'grid_1_icon',
                    'type' => 'text',
                    'display_name' => 'Grid 1 Icon',
                    'required' => '0',
                    'browse' => '0',
                    'read' => '1',
                    'edit' => '1',
                    'add' => '1',
                    'delete' => '0',
                    'details' => '{}',
                    'relation' => NULL,
                    'order' => '8',
                ),
                8 => 
                array (
                    'data_type_id' => $data_type->id,
                    'field' => 'grid_1_title',
                    'type' => 'text',
                    'display_name' => 'Grid 1 Title',
                    'required' => '0',
                    'browse' => '0',
                    'read' => '1',
                    'edit' => '1',
                    'add' => '1',
                    'delete' => '0',
                    'details' => '{}',
                    'relation' => NULL,
                    'order' => '9',
                ),
                9 => 
                array (
                    'data_type_id' => $data_type->id,
                    'field' => 'grid_1_value',
                    'type' => 'text',
                    'display_name' => 'Grid 1 Value',
                    'required' => '0',
                    'browse' => '0',
                    'read' => '1',
                    'edit' => '1',
                    'add' => '1',
                    'delete' => '0',
                    'details' => '{}',
                    'relation' => NULL,
                    'order' => '10',
                ),
                10 => 
                array (
                    'data_type_id' => $data_type->id,
                    'field' => 'grid_2_icon',
                    'type' => 'text',
                    'display_name' => 'Grid 2 Icon',
                    'required' => '0',
                    'browse' => '0',
                    'read' => '1',
                    'edit' => '1',
                    'add' => '1',
                    'delete' => '0',
                    'details' => '{}',
                    'relation' => NULL,
                    'order' => '11',
                ),
                11 => 
                array (
                    'data_type_id' => $data_type->id,
                    'field' => 'grid_2_title',
                    'type' => 'text',
                    'display_name' => 'Grid 2 Title',
                    'required' => '0',
                    'browse' => '0',
                    'read' => '1',
                    'edit' => '1',
                    'add' => '1',
                    'delete' => '0',
                    'details' => '{}',
                    'relation' => NULL,
                    'order' => '12',
                ),
                12 => 
                array (
                    'data_type_id' => $data_type->id,
                    'field' => 'grid_2_value',
                    'type' => 'text',
                    'display_name' => 'Grid 2 Value',
                    'required' => '0',
                    'browse' => '0',
                    'read' => '1',
                    'edit' => '1',
                    'add' => '1',
                    'delete' => '0',
                    'details' => '{}',
                    'relation' => NULL,
                    'order' => '13',
                ),
                13 => 
                array (
                    'data_type_id' => $data_type->id,
                    'field' => 'grid_3_icon',
                    'type' => 'text',
                    'display_name' => 'Grid 3 Icon',
                    'required' => '0',
                    'browse' => '0',
                    'read' => '1',
                    'edit' => '1',
                    'add' => '1',
                    'delete' => '0',
                    'details' => '{}',
                    'relation' => NULL,
                    'order' => '14',
                ),
                14 => 
                array (
                    'data_type_id' => $data_type->id,
                    'field' => 'grid_3_title',
                    'type' => 'text',
                    'display_name' => 'Grid 3 Title',
                    'required' => '0',
                    'browse' => '0',
                    'read' => '1',
                    'edit' => '1',
                    'add' => '1',
                    'delete' => '0',
                    'details' => '{}',
                    'relation' => NULL,
                    'order' => '15',
                ),
                15 => 
                array (
                    'data_type_id' => $data_type->id,
                    'field' => 'grid_3_value',
                    'type' => 'text',
                    'display_name' => 'Grid 3 Value',
                    'required' => '0',
                    'browse' => '0',
                    'read' => '1',
                    'edit' => '1',
                    'add' => '1',
                    'delete' => '0',
                    'details' => '{}',
                    'relation' => NULL,
                    'order' => '16',
                ),
                16 => 
                array (
                    'data_type_id' => $data_type->id,
                    'field' => 'map',
                    'type' => 'url',
                    'display_name' => 'Map',
                    'required' => '0',
                    'browse' => '0',
                    'read' => '1',
                    'edit' => '1',
                    'add' => '1',
                    'delete' => '0',
                    'details' => '{}',
                    'relation' => NULL,
                    'order' => '17',
                ),
                17 => 
                array (
                    'data_type_id' => $data_type->id,
                    'field' => 'twitter',
                    'type' => 'text',
                    'display_name' => 'Twitter',
                    'required' => '0',
                    'browse' => '0',
                    'read' => '1',
                    'edit' => '1',
                    'add' => '1',
                    'delete' => '0',
                    'details' => '{}',
                    'relation' => NULL,
                    'order' => '18',
                ),
                18 => 
                array (
                    'data_type_id' => $data_type->id,
                    'field' => 'facebook',
                    'type' => 'text',
                    'display_name' => 'Facebook',
                    'required' => '0',
                    'browse' => '0',
                    'read' => '1',
                    'edit' => '1',
                    'add' => '1',
                    'delete' => '0',
                    'details' => '{}',
                    'relation' => NULL,
                    'order' => '19',
                ),
                19 => 
                array (
                    'data_type_id' => $data_type->id,
                    'field' => 'youtube',
                    'type' => 'text',
                    'display_name' => 'Youtube',
                    'required' => '0',
                    'browse' => '0',
                    'read' => '1',
                    'edit' => '1',
                    'add' => '1',
                    'delete' => '0',
                    'details' => '{}',
                    'relation' => NULL,
                    'order' => '20',
                ),
                20 => 
                array (
                    'data_type_id' => $data_type->id,
                    'field' => 'tiktok',
                    'type' => 'text',
                    'display_name' => 'Tiktok',
                    'required' => '0',
                    'browse' => '0',
                    'read' => '1',
                    'edit' => '1',
                    'add' => '1',
                    'delete' => '0',
                    'details' => '{}',
                    'relation' => NULL,
                    'order' => '21',
                ),
                21 => 
                array (
                    'data_type_id' => $data_type->id,
                    'field' => 'instagram',
                    'type' => 'text',
                    'display_name' => 'Instagram',
                    'required' => '0',
                    'browse' => '0',
                    'read' => '1',
                    'edit' => '1',
                    'add' => '1',
                    'delete' => '0',
                    'details' => '{}',
                    'relation' => NULL,
                    'order' => '22',
                ),
                22 => 
                array (
                    'data_type_id' => $data_type->id,
                    'field' => 'discord',
                    'type' => 'text',
                    'display_name' => 'Discord',
                    'required' => '0',
                    'browse' => '0',
                    'read' => '1',
                    'edit' => '1',
                    'add' => '1',
                    'delete' => '0',
                    'details' => '{}',
                    'relation' => NULL,
                    'order' => '23',
                ),
                23 => 
                array (
                    'data_type_id' => $data_type->id,
                    'field' => 'whatsapp',
                    'type' => 'text',
                    'display_name' => 'Whatsapp',
                    'required' => '0',
                    'browse' => '0',
                    'read' => '1',
                    'edit' => '1',
                    'add' => '1',
                    'delete' => '0',
                    'details' => '{}',
                    'relation' => NULL,
                    'order' => '24',
                ),
                24 => 
                array (
                    'data_type_id' => $data_type->id,
                    'field' => 'telegram',
                    'type' => 'text',
                    'display_name' => 'Telegram',
                    'required' => '0',
                    'browse' => '0',
                    'read' => '1',
                    'edit' => '1',
                    'add' => '1',
                    'delete' => '0',
                    'details' => '{}',
                    'relation' => NULL,
                    'order' => '25',
                ),
                25 => 
                array (
                    'data_type_id' => $data_type->id,
                    'field' => 'email',
                    'type' => 'text',
                    'display_name' => 'Email',
                    'required' => '0',
                    'browse' => '1',
                    'read' => '1',
                    'edit' => '1',
                    'add' => '1',
                    'delete' => '0',
                    'details' => '{}',
                    'relation' => NULL,
                    'order' => '26',
                ),
                26 => 
                array (
                    'data_type_id' => $data_type->id,
                    'field' => 'phone1',
                    'type' => 'text',
                    'display_name' => 'Telepon 1',
                    'required' => '0',
                    'browse' => '1',
                    'read' => '1',
                    'edit' => '1',
                    'add' => '1',
                    'delete' => '0',
                    'details' => '{}',
                    'relation' => NULL,
                    'order' => '27',
                ),
                27 => 
                array (
                    'data_type_id' => $data_type->id,
                    'field' => 'phone2',
                    'type' => 'text',
                    'display_name' => 'Telepon 2',
                    'required' => '0',
                    'browse' => '1',
                    'read' => '1',
                    'edit' => '1',
                    'add' => '1',
                    'delete' => '0',
                    'details' => '{}',
                    'relation' => NULL,
                    'order' => '28',
                ),
                28 => 
                array (
                    'data_type_id' => $data_type->id,
                    'field' => 'sms_center1',
                    'type' => 'text',
                    'display_name' => 'Sms Center 1',
                    'required' => '0',
                    'browse' => '1',
                    'read' => '1',
                    'edit' => '1',
                    'add' => '1',
                    'delete' => '0',
                    'details' => '{}',
                    'relation' => NULL,
                    'order' => '29',
                ),
                29 => 
                array (
                    'data_type_id' => $data_type->id,
                    'field' => 'sms_center2',
                    'type' => 'text',
                    'display_name' => 'Sms Center 2',
                    'required' => '0',
                    'browse' => '1',
                    'read' => '1',
                    'edit' => '1',
                    'add' => '1',
                    'delete' => '0',
                    'details' => '{}',
                    'relation' => NULL,
                    'order' => '30',
                ),
                30 => 
                array (
                    'data_type_id' => $data_type->id,
                    'field' => 'created_at',
                    'type' => 'datetime',
                    'display_name' => 'Created At',
                    'required' => '0',
                    'browse' => '0',
                    'read' => '0',
                    'edit' => '0',
                    'add' => '0',
                    'delete' => '0',
                    'details' => '{}',
                    'relation' => NULL,
                    'order' => '31',
                ),
                31 => 
                array (
                    'data_type_id' => $data_type->id,
                    'field' => 'updated_at',
                    'type' => 'datetime',
                    'display_name' => 'Updated At',
                    'required' => '0',
                    'browse' => '0',
                    'read' => '0',
                    'edit' => '0',
                    'add' => '0',
                    'delete' => '0',
                    'details' => '{}',
                    'relation' => NULL,
                    'order' => '32',
                ),
                32 => 
                array (
                    'data_type_id' => $data_type->id,
                    'field' => 'deleted_at',
                    'type' => 'datetime',
                    'display_name' => 'Deleted At',
                    'required' => '0',
                    'browse' => '0',
                    'read' => '0',
                    'edit' => '0',
                    'add' => '0',
                    'delete' => '0',
                    'details' => '{}',
                    'relation' => NULL,
                    'order' => '33',
                ),
                33 => 
                array (
                    'data_type_id' => $data_type->id,
                    'field' => 'lang',
                    'type' => 'select',
                    'display_name' => 'Lang',
                    'required' => '1',
                    'browse' => '1',
                    'read' => '1',
                    'edit' => '1',
                    'add' => '1',
                    'delete' => '1',
                    'details' => '{
"size": 12,
"items": [
{
"label": "Indonesia",
"value": "id"
},
{
"label": "English",
"value": "en"
}
]
}',
                    'relation' => NULL,
                    'order' => '34',
                ),
            ));

            \DB::commit();
        } catch(Exception $e) {
            \DB::rollBack();

            throw new Exception('exception occur ' . $e);
        }
    }
}

